// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// content/profile.json
var profile_default = {
  headline: "Head of Digital Solutions at CUBONIC | 18+ Years in Digital Platforms, Marketplaces, Connected Products, Cloud, Mobility & Product GTM/Strategy",
  positions: [
    {
      company: "CUBONIC",
      title: "Head of Digital Solutions",
      location: "Berlin, Germany",
      start: "Feb 2024",
      end: null,
      summary: "Leading digital transformation across the business \u2014 AI strategy, local & private LLM deployments, agentic solutions, and the digital backbone for future mobility products."
    },
    {
      company: "HirePlusPlus",
      title: "Advisory Board Member",
      location: "Berlin, Germany",
      start: "Aug 2023",
      end: "Jul 2024",
      summary: "Advising on product strategy and go-to-market for an HR-tech platform."
    },
    {
      company: "AutoScout24",
      title: "Head of Product / Head of Apps",
      location: "Munich, Germany",
      start: "Aug 2022",
      end: "Jan 2024",
      summary: "Owned vision, strategy and roadmap for the native apps of Europe's largest car marketplace \u2014 iOS, Android and all white-label apps (AutoTrader, Gebrauchtwagen.de) \u2014 leading 4 senior PMs and 24 engineers. Grew organic user acquisition 30% across European markets, doubled app engagement, improved conversion 23%, and lifted app advertising & media revenue 10%."
    },
    {
      company: "Cazoo",
      title: "Senior Product Manager",
      location: "Munich, Germany",
      start: "Jul 2021",
      end: "Aug 2022",
      summary: "After Cazoo's acquisition of Cluno, responsible for product across asset financing, fleet management and car production. Grew subscription revenue 30% and vehicle contribution margin 50%; helped launch the Cazoo retail proposition across 5 European markets and was part of the product leadership team when Cazoo listed on the NYSE in 2021."
    },
    {
      company: "Cluno",
      title: "Senior Product Manager",
      location: "Munich, Germany",
      start: "Feb 2019",
      end: "Aug 2022",
      summary: "Owned the end-to-end digital transformation of Germany's car-subscription pioneer \u2014 partner platform connecting 131 dealerships plus logistics, refurbisher and assessor partners, digital handover, damage reporting, OCR fine handling, automated invoicing, and the Cluno iOS & Android apps. Cut operating costs ~25% through lean, automated operations."
    },
    {
      company: "MERZ Group",
      title: "Head of Software / Product Development",
      location: "Aalen, Germany",
      start: "Sep 2015",
      end: "Jan 2019",
      summary: "Led 7 software teams building computer-vision products for Carl Zeiss IMT \u2014 industrial metrology and car-body measurement \u2014 while consulting on manufacturing quality at Porsche, Daimler, VW, Volvo and Ford plants. Architected the core point-cloud processing product, ran business development from first contact to closed deal, and received a Microsoft MVP award."
    },
    {
      company: "MERZ Group",
      title: "Engineering Lead",
      location: "Aalen, Germany",
      start: "May 2013",
      end: "Sep 2015",
      summary: "Built ZEISS Reverse Engineering (C++/C#/WPF on the ACIS kernel) \u2014 CAD reverse engineering and tool correction for mould making \u2014 and engineered robot-based automated inspection combining optical sensors with FANUC, KUKA and ABB robots."
    },
    {
      company: "Tata Consultancy Services",
      title: "IT Analyst",
      location: "India",
      start: "Sep 2008",
      end: "May 2013",
      summary: "Embedded systems and CAD software across regulated industries: avionics for the SARAS aircraft programme at National Aerospace Laboratories (DO-178B), sensor firmware for Anderson-Negele, assembly-level V&V for Meggitt flight displays \u2014 then technical lead building ZEISS Reverse Engineering from scratch, the product that took me to Germany."
    }
  ],
  education: [
    {
      school: "Amrita Vishwa Vidyapeetham",
      degree: "Bachelor of Technology (B.Tech.), Electrical & Electronics Engineering",
      period: "2004 \u2014 2008",
      activities: "Indian Society of Electrical and Electronics Engineers, IEEE Seminar"
    },
    {
      school: "Kendriya Vidyalaya",
      degree: "XII (CBSE)",
      period: "1992 \u2014 2004",
      activities: "Debate team, elocution, house prefect, science exhibitions, cultural & arts committee, regional and national level sports"
    }
  ],
  skillGroups: [
    {
      label: "Product & Leadership",
      skills: [
        "Product Management",
        "Product Strategy",
        "Product Vision",
        "Product Discovery",
        "Go-to-Market Strategy",
        "Digital Strategy",
        "Leadership",
        "Team Management",
        "Coaching & Mentoring",
        "Change Management",
        "Revenue & Profit Growth"
      ]
    },
    {
      label: "AI & Emerging Tech",
      skills: [
        "AI Strategy",
        "Local LLMs",
        "Artificial Intelligence (AI)",
        "Agentic Systems",
        "Solution Architecture",
        "Robotics",
        "Augmented Reality",
        "Embedded Systems"
      ]
    },
    {
      label: "Domains",
      skills: [
        "Online Marketplaces",
        "E-Commerce",
        "SaaS",
        "B2B & B2C",
        "Supply Chain Management",
        "Lean Operations",
        "User Experience (UX)"
      ]
    },
    {
      label: "Engineering",
      skills: [
        "C++",
        "C#",
        "Python",
        "TypeScript",
        "Qt",
        "OpenCV & Point Clouds",
        "Android",
        "iOS",
        "Salesforce",
        "Tableau & Amplitude",
        "SDLC",
        "Agile Project Management"
      ]
    }
  ],
  topEndorsed: [
    {
      name: "C++",
      count: 24
    },
    {
      name: ".NET",
      count: 20
    },
    {
      name: "C",
      count: 12
    },
    {
      name: "Product Management",
      count: 10
    },
    {
      name: "Requirements Analysis",
      count: 9
    },
    {
      name: "Software Development",
      count: 9
    },
    {
      name: "Software Project Management",
      count: 7
    },
    {
      name: "Coaching & Mentoring",
      count: 6
    },
    {
      name: "Analytical Skills",
      count: 6
    }
  ],
  languages: [],
  certifications: [
    {
      name: ".NET 4.0 & WPF",
      authority: "PC College, Stuttgart, Germany",
      year: "2011"
    },
    {
      name: "FANUC Robot Handling and Dual Check Safety",
      authority: "FANUC Robotics Deutschland GmbH",
      year: "2015"
    },
    {
      name: "DMIS CMM Programming",
      authority: "ZEISS Academy, Germany",
      year: "2018"
    }
  ],
  honors: [],
  volunteering: []
};

// content/site.json
var site_default = {
  heroFirstName: "UTPAL",
  heroLastName: "DAS",
  tagline: "Father \xB7 Builder \xB7 Problem Solver",
  heroRole: "Head of Digital Solutions \xB7 CUBONIC",
  heroBio: "18+ years shipping software that had to work \u2014 cockpit displays, CAD, robot metrology, Europe's largest car marketplace and autonomous movers. Now I hold AI to the same bar.",
  manifestoLead: "Planes. Production lines. Marketplaces. Autonomous vehicles.",
  manifestoMiddle: "Eighteen years of software that had to work.",
  manifestoEnd: "That's the bar",
  manifestoAccent: "AI has to clear.",
  manifestoFootnote: "\u2014 the thesis behind everything below.",
  dreamLabel: "The next dream",
  dreamLine: "One day, governments will build correctional facilities for bad AI agents.",
  dreamAccent: "I'd like to build them.",
  pillars: [
    {
      title: "Transparency",
      note: "Say what's true, even when it's inconvenient. It's how trust starts."
    },
    {
      title: "Trust",
      note: "I don't trust words. I trust work. Judge people \u2014 and yourself \u2014 by what ships."
    },
    {
      title: "Positivity",
      note: "Momentum beats perfection. Failures are the team's; wins are the team's."
    }
  ],
  signatureQuotes: [
    "Problem-obsessed, not solution-obsessed.",
    "Save cost. Save time. That's what an engineer does.",
    "MLP, not MVP \u2014 Most Lovable Product.",
    "We failed as a team. We succeeded as a team.",
    "Flying a rocket ship while it's being built."
  ],
  contactEmail: "utpal.inbox@hotmail.com",
  linkedin: "https://www.linkedin.com/in/iamdasutpal/",
  github: "https://github.com/UtpalDasLabs",
  location: "Berlin, Germany"
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Utpal Das's public profile: name, headline, bio, location, and links (LinkedIn, GitHub, email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ profile: profile_default, site: site_default }, null, 2) }],
    structuredContent: { profile: profile_default, site: site_default }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// content/projects.json
var projects_default = {
  projects: [
    {
      id: "agentic-platform",
      title: "Agentic AI Platform",
      category: "AI Systems",
      year: "2025",
      tags: [
        "AGENTIC AI",
        "LLM ORCHESTRATION"
      ],
      companies: [
        "cubonic"
      ],
      description: "An internal platform for building multi-agent workflows on top of local and hosted LLMs \u2014 tool use, memory, guardrails, and human-in-the-loop review for mobility and operations teams.",
      oneLiner: "Enterprise AI that reaches past chat \u2014 agents that use tools, keep context, and hand risky work back to a human.",
      role: "Head of Digital Solutions",
      scale: "Mobility & operations teams",
      period: "2025 \u2013 present",
      stack: [
        "Local & hosted LLMs",
        "Multi-agent orchestration",
        "Tool use",
        "Memory",
        "Guardrails"
      ],
      problem: "Most enterprise AI stops at a chat window: it can answer, but it can't act, it forgets everything between sessions, and there is no safe way to let it touch a real system. The teams who would benefit most \u2014 mobility operations \u2014 need AI that reaches into tools and data, while staying inside limits a business can defend.",
      approach: [
        "Built an internal platform for composing multi-agent workflows rather than one-off bots, so teams assemble what they need instead of commissioning a new integration each time.",
        "Gave agents real capability \u2014 tool use and memory \u2014 so they can carry out a task end to end instead of returning text for a human to re-key.",
        "Wrapped every workflow in guardrails, with human-in-the-loop review that triggers when the risk of an action is too high.",
        "Ran it on both local and hosted models, so sensitive workloads can stay private without giving up frontier capability elsewhere."
      ],
      outcome: "A platform mobility and operations teams build on, where agents do real work under explicit limits \u2014 and the first step toward the accountability layer autonomous agents will need.",
      story: [
        "Agents are the next interface \u2014 and the next attack surface. Most enterprise AI still stops at chat. We're building past that: multi-agent workflows that can actually reach into tools, remember context, and hand work back to a human when the risk is too high.",
        "The bigger bet: as agents get more autonomy, someone has to build the accountability layer around them \u2014 systems that catch bad behaviour, correct it, and only then hand autonomy back. This platform is the first honest step toward that."
      ],
      link: "www.cubonic.de",
      coverImage: "/covers/ai-a.svg",
      coverHeadline: "MULTI-AGENT",
      coverCaption: "tool use \xB7 memory \xB7 guardrails"
    },
    {
      id: "cubonic-digital",
      title: "CUBONIC \u2014 Digital Infrastructure for Last-Mile Mobility",
      category: "Mobility & Marketplaces",
      year: "2024\u2013present",
      tags: [
        "CONNECTED VEHICLE",
        "LAST MILE"
      ],
      companies: [
        "cubonic"
      ],
      description: "Building CUBONIC's digital infrastructure from the ground up \u2014 connecting the vehicle and its autonomous driving stack to the wider ecosystem behind sustainable last-mile mobility: autonomous, connected electric light commercial vehicles.",
      oneLiner: "The digital backbone for autonomous, connected electric vans \u2014 built from the ground up.",
      role: "Head of Digital Solutions",
      scale: "Vehicle \xB7 autonomous driving \xB7 ecosystem",
      period: "Feb 2024 \u2013 present",
      stack: [
        "Connected vehicle",
        "Autonomous driving",
        "Cloud platform",
        "Fleet ecosystem"
      ],
      problem: "A new vehicle programme is not just a vehicle. An autonomous, connected eLCV only delivers last-mile mobility if there is a digital layer underneath it \u2014 connecting what the vehicle knows to the operators, customers and systems around it. At CUBONIC that layer did not exist yet; it had to be built from the ground up, in parallel with the vehicle itself.",
      approach: [
        "Built the digital infrastructure from zero rather than assembling it from off-the-shelf fleet tooling, so it fits an autonomous vehicle rather than a conventional one.",
        "Connected the vehicle and its autonomous driving stack into the wider CUBONIC ecosystem, so vehicle data becomes operational capability.",
        "Led AI strategy, private LLM deployment and agentic systems as part of the same backbone \u2014 the platform, the local model stack and the governance model are one programme, not three.",
        "Kept it aimed at the actual business outcome: sustainable last-mile delivery that works commercially, not a technology demonstration."
      ],
      outcome: "The digital foundation the CUBONIC vehicle and ecosystem run on \u2014 and the platform the agentic and private-LLM work is built into.",
      link: "www.cubonic.de",
      coverImage: "/covers/mobility-a.svg",
      coverHeadline: "LAST MILE, ELECTRIC",
      coverCaption: "autonomous \xB7 connected \xB7 eLCV"
    },
    {
      id: "autoscout24-apps",
      title: "AutoScout24 Mobile Apps",
      category: "Mobility & Marketplaces",
      year: "2022\u20132024",
      tags: [
        "IOS & ANDROID",
        "MARKETPLACE"
      ],
      companies: [
        "autoscout24"
      ],
      description: "Head of Product for the native apps of Europe's largest car marketplace \u2014 search, favorites, price-drop alerts, dealer contact and selling flows across 2M+ listings, plus the AutoTrader and Gebrauchtwagen.de white-label apps. Led 4 senior PMs and 24 engineers; grew organic user acquisition 30% across European markets, doubled engagement, improved conversion 23% and lifted app advertising revenue 10%.",
      oneLiner: "Europe's largest car marketplace, in your pocket \u2014 four apps, one team, four numbers moved at once.",
      role: "Head of Product / Head of Apps",
      team: "4 senior PMs \xB7 24 engineers",
      scale: "2M+ live listings \xB7 4 apps \xB7 European markets",
      period: "Aug 2022 \u2013 Jan 2024",
      stack: [
        "iOS",
        "Android",
        "White-label platform",
        "Amplitude",
        "A/B testing"
      ],
      metrics: [
        {
          value: "+30%",
          label: "organic acquisition",
          note: "across European markets"
        },
        {
          value: "2\xD7",
          label: "app engagement"
        },
        {
          value: "+23%",
          label: "conversion"
        },
        {
          value: "+10%",
          label: "app ad revenue"
        }
      ],
      problem: "Own the vision, strategy and roadmap for the native apps of Europe's largest car marketplace \u2014 iOS, Android and the white-label apps (AutoTrader, Gebrauchtwagen.de) \u2014 and move four numbers at once: organic acquisition, engagement, conversion and app advertising revenue. All of it across multiple European markets, on a marketplace where private buyers and professional dealers want very different things from the same product.",
      approach: [
        "Made search and discovery the core loop \u2014 filters, saved searches and a notepad for favourites, so returning to a shortlist is one tap rather than a new search.",
        "Turned price-drop alerts into the retention engine: push notifications on saved cars bring users back at exactly the moment their decision changes.",
        "Closed the buyer\u2013dealer gap with direct dealer contact and verified, authentic dealer reviews on every listing.",
        "Opened the sell side in-app \u2014 photo upload and a free value check, so listing a car takes minutes on a phone.",
        "Ran AutoScout24, AutoTrader and Gebrauchtwagen.de from one white-label platform, so a single team's work shipped to every market.",
        "Kept decisions data-informed, pairing product analytics with insight from the international offices and business stakeholders."
      ],
      outcome: "Organic user acquisition up 30% across European markets, app engagement doubled, conversion up 23% and app advertising revenue up 10% \u2014 delivered by a lean app team of 4 senior PMs and 24 engineers owning a business result at marketplace scale.",
      recommendationRef: "Nikita Belokopytov",
      story: [
        "Two million listings. Millions of users. One iOS and one Android app carrying the whole marketplace in your pocket \u2014 plus the white-label AutoTrader and Gebrauchtwagen.de apps on the same codebase.",
        "Coming from Cluno, I brought the same instinct: connect the two journeys \u2014 the buyer's journey and the vehicle's journey \u2014 inside one engine. Every price-drop notification, every dealer contact, every save is a touch point in a much larger system.",
        "Numbers moved: +30% organic acquisition across markets, 2\xD7 engagement, +23% conversion, +10% in-app ad revenue. Senior PMs, app marketing and engineers. The proudest part isn't the metrics \u2014 it's that a lean app team owned a business result at that scale."
      ],
      link: "https://www.autoscout24.de/",
      coverImage: "/covers/mobility-a.svg",
      coverVideo: "/videos/as24.mp4",
      coverPoster: "/videos/posters/as24.jpg"
    },
    {
      id: "local-llm-stack",
      title: "Local LLM Stack",
      category: "AI Systems",
      year: "2025",
      tags: [
        "LOCAL LLMS",
        "PRIVACY"
      ],
      companies: [
        "cubonic"
      ],
      description: "Private, on-prem LLM deployment stack for regulated data \u2014 model routing, quantization, evaluation harness, and observability, so sensitive workloads never leave the perimeter.",
      oneLiner: "Frontier AI on regulated data \u2014 private by architecture, not by policy.",
      role: "Head of Digital Solutions",
      period: "2025 \u2013 present",
      stack: [
        "Local LLMs",
        "Model routing",
        "Quantization",
        "Evaluation harness",
        "Observability"
      ],
      problem: "Regulated data cannot leave the perimeter, but the useful models mostly live outside it. The usual answer is a policy promising nobody will paste anything sensitive into a chatbot \u2014 which is not an architecture, and does not survive contact with a deadline.",
      approach: [
        "Routed requests across model sizes, so each workload runs on the smallest model that actually does the job.",
        "Tuned quantization per workload to make on-prem deployment economic instead of theoretical.",
        "Built an evaluation harness that tells you when a model regresses \u2014 the difference between shipping AI and hoping.",
        "Added observability so nothing runs blind, and every answer can be traced."
      ],
      outcome: "Sensitive workloads stay inside the perimeter by architecture. Private deployment became a default option for the business rather than a special case.",
      story: [
        "In 2008, I dreamt of a world where I could type in plain English and get machine code back. In 2017, I trained my first neural net on industrial CT scans. In 2025, that dream is a product problem: how do you deploy it without leaking a single row of regulated data?",
        "This stack answers that. Model routing across sizes, quantization tuned per workload, an evaluation harness that actually tells you when a model regresses, and observability so nothing runs blind. Sensitive workloads stay inside the perimeter \u2014 by architecture, not by policy."
      ],
      coverImage: "/covers/ai-b.svg",
      coverHeadline: "ON-PREM",
      coverCaption: "private by design, zero perimeter exit"
    },
    {
      id: "cluno-partner-platform",
      title: "Cluno \u2014 Partner Platform & Business Engine",
      category: "Mobility & Marketplaces",
      year: "2019\u20132022",
      tags: [
        "B2B PLATFORM",
        "OPERATIONS"
      ],
      companies: [
        "cluno"
      ],
      description: "One platform connecting Cluno with its whole partner ecosystem \u2014 131 dealerships, logistics carriers, refurbishers and vehicle assessors across Germany, with 100% dealership adoption and nearly 1,000 vehicles ordered through it. Order confirmation, scheduling, digital handover protocols, invoicing, one-click remarketing auctions via Auto1 and vehicle-health reporting replaced email-and-spreadsheet workflows, letting a lean operations team run a growing subscription fleet. Cluno was later acquired by Cazoo.",
      oneLiner: "The operating engine for a car-subscription business \u2014 one platform for every partner, from order to remarketing.",
      role: "Senior Product Manager \u2014 end-to-end owner",
      team: "Cross-functional product & engineering",
      scale: "131 dealerships \xB7 nationwide partner network",
      period: "Mar 2019 \u2013 Jul 2022",
      stack: [
        "Partner portal",
        "Salesforce",
        "Auto1 integration",
        "iOS",
        "Android"
      ],
      metrics: [
        {
          value: "131",
          label: "dealerships connected"
        },
        {
          value: "100%",
          label: "dealership adoption"
        },
        {
          value: "~1,000",
          label: "vehicles ordered",
          note: "through the platform"
        }
      ],
      problem: "Cluno was a car-subscription startup with real ambition and no operating engine: dealerships, logistics carriers, refurbishers and assessors were all coordinated by email and spreadsheets. That works until volume arrives \u2014 then every new vehicle costs manual effort, and growth is capped by the operations team's inbox.",
      approach: [
        "Owned the whole journey from the moment a customer says 'I want this car' \u2014 Schufa credit checks, billing, insurance, refurbishment, remarketing, logistics and handover.",
        "Built one partner portal for dealerships, carriers, refurbishers and assessors, replacing email-and-spreadsheet workflows with order confirmation, scheduling and invoicing.",
        "Added one-click remarketing auctions via Auto1, so end-of-life vehicles left the fleet without a manual process.",
        "Shipped digital handover protocols and vehicle-health reporting, plus the customer's iOS and Android apps.",
        "Stitched the two parallel journeys \u2014 the customer's lifecycle and the vehicle's lifecycle \u2014 into a single system."
      ],
      outcome: "A lean operations team could run a growing subscription fleet: 131 dealerships connected with 100% adoption and nearly 1,000 vehicles ordered through the platform. That engine is what Cazoo acquired.",
      recommendationRef: "Dr. Veronika von Heise-Rotenburg",
      story: [
        "After a decade in embedded systems and industrial software, I made a hard pivot into the cloud. Cluno was the landing site \u2014 a small car-subscription startup in Munich with big ambitions and no operating engine.",
        "My job was to build that engine. Not rebuild \u2014 build. From the moment a customer said 'I want this car,' I owned the whole journey: Schufa credit checks, billing, insurance, refurb, remarketing via Auto1, logistics, and a fully digital handover with zero paper. On top of that, iOS and Android apps for the customer, and a partner portal for the dealers, carriers, and refurbishers.",
        "This is where I stopped talking about MVPs and started talking about MLPs \u2014 Most Lovable Products. Ship small, but ship something people love. Love means trust. You keep building on trust.",
        "The real insight of Cluno: two journeys running in parallel \u2014 the customer's lifecycle and the vehicle's lifecycle \u2014 meeting for a while, then parting. Stitch them into one system and you have a business engine. That engine is what Cazoo bought."
      ],
      coverImage: "/covers/mobility-b.svg",
      coverVideo: "/videos/cluno-app.mp4",
      coverPoster: "/videos/posters/cluno-app.jpg"
    },
    {
      id: "apollo-ar-projection",
      title: "Extend3D \u2014 Werklicht AR Projection",
      category: "Industrial & Vision",
      year: "2017\u20132018",
      tags: [
        "AUGMENTED REALITY",
        "INDUSTRY 4.0"
      ],
      companies: [
        "extend3d"
      ],
      description: "Architect and scrum master for Extend3D's Werklicht laser/video projection system \u2014 augmented reality that projects CAD data directly onto physical parts on the automotive shop floor. Qt, C++ and the CGM modeler kernel, including a 3D data framework importing GOM, Polyworks and SpaceClaim formats.",
      oneLiner: "Augmented reality for the shop floor \u2014 CAD data projected straight onto the physical part.",
      role: "Architect & Scrum Master (effectively CTO/CPO for the client)",
      team: "Three-person startup, delivered via MERZ",
      period: "Aug 2017 \u2013 Sep 2018",
      stack: [
        "Qt",
        "C++",
        "CGM modeler kernel",
        "GOM / Polyworks / SpaceClaim import"
      ],
      problem: "Extend3D had a beautiful piece of mathematics \u2014 an algorithm to transform 3D into 2D and project it back onto real objects at true scale \u2014 plus the hardware to do it. What they did not have was the software or the product thinking to turn it into something an automotive plant could use.",
      approach: [
        "Acted as architect and scrum master, effectively the CTO/CPO for someone else's company as a third party.",
        "Built the Werklicht laser and video projection system on Qt, C++ and the CGM modeler kernel.",
        "Wrote a 3D data framework importing the formats customers actually had \u2014 GOM, Polyworks and SpaceClaim.",
        "Worked startup-style: nothing on the shelf, every test rig ordered and every invoice chased personally."
      ],
      outcome: "An operator on the line sees the design overlaid on the part itself \u2014 CAD projected directly onto a car body or aircraft panel. Still the reference point for what 'AR on the shop floor' should mean.",
      story: [
        "Extend3D was three people with a beautiful piece of math \u2014 an algorithm to transform 3D into 2D and project it back onto real objects at real scale. They had the hardware and the mathematics. They needed the software and the product thinking.",
        "This was my first taste of being effectively the CTO/CPO for someone else's company \u2014 as a third party, from Merz. Nothing was on the shelf: every test rig had to be ordered, every invoice chased. Big-company reflexes don't work in a startup.",
        "What we built projects CAD data straight onto a car body or aircraft panel \u2014 the operator sees the design overlaid on the part itself. That collaboration is still what I think of when someone says 'AR on the shop floor.'"
      ],
      link: "https://www.extend3d.com/de/produkt/werklicht-video/",
      coverImage: "/covers/engineering-a.svg"
    },
    {
      id: "asset-financing",
      title: "Cazoo \u2014 Asset Financing & European Rollout",
      category: "Mobility & Marketplaces",
      year: "2021\u20132022",
      tags: [
        "FINTECH",
        "AUTOMOTIVE"
      ],
      companies: [
        "cazoo"
      ],
      description: "After Cazoo's acquisition of Cluno, led product for asset financing, fleet management and car production \u2014 the systems that financed and tracked the subscription fleet. Contributed to a 30% rise in subscription revenue and a 50% improvement in vehicle contribution margin, and supported the Cazoo retail launch across 5 European markets.",
      oneLiner: "Financing and moving a subscription fleet across Europe \u2014 while the company was going public.",
      role: "Senior Product Manager \u2014 asset financing, fleet & production",
      scale: "5 European markets \xB7 multiple credit lines",
      period: "Nov 2021 \u2013 Jul 2022",
      stack: [
        "Asset financing",
        "Fleet management",
        "Logistics planning"
      ],
      metrics: [
        {
          value: "+30%",
          label: "subscription revenue"
        },
        {
          value: "+50%",
          label: "vehicle contribution margin"
        },
        {
          value: "5",
          label: "European markets",
          note: "retail launch"
        }
      ],
      problem: "Cluno was acquired by Cazoo mid-flight and Munich became the European HQ. The subscription fleet now had to be financed across multiple credit lines and moved across borders \u2014 while the company listed on the NYSE and every market applied its own regulation.",
      approach: [
        "Stood up asset financing across multiple credit lines, and the systems that tracked what each vehicle was worth.",
        "Built first-mile, mid-mile and last-mile logistics for whole truckloads of cars across Germany, France and Spain \u2014 refurbishment centres, distribution hubs and home delivery.",
        "Took regulation market by market rather than waiting for one perfect pan-European product.",
        "Supported the Cazoo retail proposition launch across five European markets."
      ],
      outcome: "Subscription revenue up 30% and vehicle contribution margin up 50%, with the retail proposition live in five markets \u2014 delivered while the business was being rebuilt around an IPO.",
      recommendationRef: "Louis Badcock",
      story: [
        "Cluno was acquired by Cazoo mid-flight. Munich became the European HQ. Overnight I was reporting into the Cazoo CPO, in the room for the IPO conversations, with equity that suddenly meant working for yourself as well as the company.",
        "Flying a rocket ship while it's being built. That's the honest description. We stood up asset financing across multiple credit lines, and built the first-mile / mid-mile / last-mile logistics for whole truckloads of cars across Germany, France, and Spain \u2014 refurb centres, distribution hubs, home delivery.",
        "The hardest part wasn't the tech; it was regulation, region by region. You couldn't wait for a perfect product. You shipped what worked, learned, iterated. +30% subscription revenue. +50% vehicle contribution margin. Retail launch in 5 markets."
      ],
      coverImage: "/covers/mobility-b.svg",
      coverVideo: "/videos/hub-check.mp4",
      coverPoster: "/videos/posters/hub-check.jpg"
    },
    {
      id: "eicas-avionics",
      title: "Avionics & Safety-Critical Systems",
      category: "Avionics & Embedded",
      year: "2008\u20132011",
      tags: [
        "AVIONICS",
        "SAFETY-CRITICAL"
      ],
      companies: [
        "nal",
        "meggitt",
        "negele"
      ],
      description: "Engine Indication and Crew Alert System for the pilot's primary display of NAL's SARAS aircraft \u2014 flight management, GPS position, fuel indication and ground-maintenance modules in C++ under DO-178B; assembly-level V&V of the TI DSP code in Meggitt's secondary flight display; and C firmware for Anderson-Negele food & pharma sensor systems.",
      oneLiner: "Software that had to fly \u2014 the pilot's primary display, under DO-178B.",
      role: "IT Analyst \u2192 technical anchor",
      scale: "3 safety-critical programmes",
      period: "Dec 2008 \u2013 Feb 2011",
      stack: [
        "C++",
        "DO-178B",
        "TI DSP assembly",
        "C firmware",
        "I\xB2C",
        "RS-232"
      ],
      problem: "Avionics software has no tolerance for cleverness. The Engine Indication and Crew Alert System drives the pilot's primary display on NAL's SARAS aircraft \u2014 flight management, GPS position, fuel indication, ground maintenance \u2014 in real time, under DO-178B, where every line has to be justified.",
      approach: [
        "Built the EICAS modules in C++ under DO-178B: flight management, GPS position, fuel indication and ground maintenance.",
        "Performed assembly-level verification and validation of the TI DSP code in Meggitt's secondary flight display \u2014 six months of hunting McCabe complexity in code written by teams in the UK.",
        "Owned an embedded project end to end for Anderson-Negele: a microcontroller inside a food-and-pharma sensor acting as a mini-router \u2014 turbidity and viscosity readings out over I\xB2C, Wi-Fi and RS-232.",
        "Became the technical anchor for a small team \u2014 leadership earned through the work rather than granted by title."
      ],
      outcome: "Three safety-critical programmes delivered, and a permanent change in how I read a function. It also showed me the limit I wanted to escape: with real-time constraints, the memory budget is the point \u2014 I wanted problems where the product was.",
      story: [
        "My first job out of college. Software that had to fly. EICAS \u2014 the pilot's primary display for NAL's SARAS aircraft \u2014 under DO-178B, with all the discipline that implies. Flight management, GPS position, fuel indication, ground maintenance. C++, real-time, no room for cleverness.",
        "This was also my first taste of leadership: not as a manager with disciplinary authority, but as the technical anchor for a small group of friends. Mentoring, guiding, showing them where to look. It stuck as my definition of leadership \u2014 earn it through the work.",
        "Then came six months of code review \u2014 hunting McCabe complexity in code written by teams in the UK. Boring, but it permanently changed how I read a function.",
        "In 2010, Anderson-Negele: a one-man-army embedded project. A microcontroller inside a food-and-pharma sensor, acting as a mini-router \u2014 turbidity and viscosity readings out to I\xB2C for the display, over Wi-Fi for subscribers, over RS-232 for downstream systems. First time I owned something end to end.",
        "By the end of this chapter I was frustrated. Real-time constraints meant I couldn't build big systems. So I started looking for problems where the memory budget wasn't the point \u2014 the product was."
      ],
      coverImage: "/covers/avionics-a.svg",
      coverVideo: "/videos/eicas.mp4",
      coverPoster: "/videos/posters/eicas.jpg"
    },
    {
      id: "ai-strategy",
      title: "AI Strategy & Governance",
      category: "AI Systems",
      year: "2024",
      tags: [
        "AI STRATEGY",
        "LEADERSHIP"
      ],
      companies: [
        "cubonic"
      ],
      description: "A pragmatic AI operating model: opportunity mapping, capability roadmap, risk & governance framework, and vendor vs. build decisions \u2014 turning executive intent into shipped systems.",
      oneLiner: "From 'we know we need AI' to shipped systems \u2014 an operating model a CFO can defend.",
      role: "Head of Digital Solutions",
      period: "2024 \u2013 present",
      stack: [
        "Opportunity mapping",
        "Capability roadmap",
        "Risk & governance",
        "Build vs. buy"
      ],
      problem: "Every executive team lands on the same curve: they know they need AI, they don't know where to start, and they don't want to become someone else's training data. The gap is rarely technology \u2014 it's the absence of an operating model that connects intent to something shipped.",
      approach: [
        "Mapped opportunities against real business outcomes \u2014 save cost, save time \u2014 rather than against what demos well.",
        "Built a capability roadmap that respects the systems and skills already in the building.",
        "Wrote a governance and risk framework a CFO can defend, not just an engineering team.",
        "Made honest build-vs-buy calls that don't optimise for looking impressive."
      ],
      outcome: "A repeatable path from executive intent to systems in production \u2014 the framework behind the agentic platform and the private LLM stack.",
      story: [
        "Every executive team I meet is somewhere on the same curve: 'we know we need AI, we don't know where to start, and we don't want to become someone else's training data.'",
        "This is the framework I use to move them from intent to shipped systems \u2014 opportunity mapping against real business outcomes (save cost, save time \u2014 that's what an engineer does), a capability roadmap that respects what already exists, a governance and risk model that a CFO can defend, and honest build-vs-buy calls that don't optimize for looking impressive."
      ],
      coverImage: "/covers/ai-a.svg",
      coverHeadline: "ROADMAP",
      coverCaption: "opportunity map \u2192 governance \u2192 shipped systems"
    },
    {
      id: "digital-handover",
      title: "Digital Handover & Damage Reporting",
      category: "Mobility & Marketplaces",
      year: "2019\u20132022",
      tags: [
        "MOBILE APPS",
        "OPERATIONS"
      ],
      companies: [
        "cluno"
      ],
      description: "A three-step digital protocol replacing paper checklists for every vehicle transaction \u2014 3,700+ digital handovers, 54% of them home deliveries, and a beta rollout with 100% successful handovers. Real-time handover status in Salesforce, plus in-app damage reporting with dynamic questionnaires, photos and location sharing that cut per-unit repair costs 5\u201310%.",
      oneLiner: "Killing the paper checklist at the one moment a customer touches your operation.",
      role: "Senior Product Manager",
      scale: "Nationwide vehicle operations",
      period: "Nov 2019 \u2013 Jul 2022",
      stack: [
        "iOS",
        "Android",
        "Salesforce",
        "Dynamic questionnaires"
      ],
      metrics: [
        {
          value: "3,700+",
          label: "digital handovers"
        },
        {
          value: "54%",
          label: "at the customer's home"
        },
        {
          value: "100%",
          label: "successful beta rollout"
        },
        {
          value: "5\u201310%",
          label: "lower repair cost",
          note: "per unit"
        }
      ],
      problem: "The handover is the single moment a customer physically touches your operational reality \u2014 and it was run on paper checklists. Paper means no real-time status, no structured damage record, and a workshop that only discovers what it is dealing with when the car is already on the ramp.",
      approach: [
        "Replaced the checklist with a three-step digital protocol, signed on a phone.",
        "Streamed handover status into Salesforce in real time, so operations could see the fleet as it moved.",
        "Built in-app damage reporting with dynamic questionnaires, photos and location sharing \u2014 the workshop knew what was coming before the car arrived.",
        "Shipped it MLP-style: a lovable minimum first, then let the numbers grow into the vision."
      ],
      outcome: "3,700+ digital handovers with 54% at the customer's home, a beta rollout with 100% successful handovers, and per-unit repair costs down 5\u201310%.",
      recommendationRef: "Annika Kaps",
      story: [
        "The handover is the single moment a customer touches your operational reality. Paper checklists were the norm. We killed them.",
        "A three-step digital protocol, signed on a phone, streamed to Salesforce in real time. In-app damage reporting with dynamic questionnaires, photos, and location sharing so the workshop already knew what it was dealing with when the car arrived. 3,700+ handovers, 54% at the customer's home, and per-unit repair costs down 5\u201310%. MLP philosophy in practice \u2014 ship a lovable minimum, learn, and let the numbers grow into the vision."
      ],
      link: "https://apps.apple.com/de/app/cluno-auto-abo/id1434401969",
      coverImage: "/covers/mobility-a.svg",
      coverVideo: "/videos/handover.mp4",
      coverPoster: "/videos/posters/handover.jpg"
    },
    {
      id: "operations-automation",
      title: "Operations & Logistics Automation",
      category: "Mobility & Marketplaces",
      year: "2019\u20132021",
      tags: [
        "SUPPLY CHAIN",
        "AUTOMATION"
      ],
      companies: [
        "cluno",
        "cazoo"
      ],
      description: "The systems behind lean operations: a work-order management system mapping every job and invoice line item across logistics, maintenance, repair and inspection; OCR-based fine handling from scanned police notice to customer invoice; automated monthly invoicing; on-demand vehicle-health reports; S&OP and mid-mile planning; and the Glide Intake app for VIN-scan check-in. Net effect: over 80% less manual effort on vehicle availability alone.",
      oneLiner: "Fleets don't fail at the exciting parts \u2014 so we automated the boring ones.",
      role: "Senior Product Manager \u2014 operations & logistics",
      scale: "Subscription fleet operations, Germany",
      period: "Mar 2019 \u2013 Nov 2021",
      stack: [
        "OCR",
        "Work-order management",
        "Automated invoicing",
        "S&OP",
        "VIN scanning"
      ],
      metrics: [
        {
          value: "80%+",
          label: "less manual effort",
          note: "on vehicle availability alone"
        }
      ],
      problem: "Fleets fail at the boring parts: a mis-typed VIN, a police notice that never becomes an invoice, a maintenance job nobody billed for. Each one is small; together they cap how large a fleet a lean operations team can run.",
      approach: [
        "Built a work-order management system mapping every job and invoice line item across logistics, maintenance, repair and inspection.",
        "Automated monthly invoicing so billing stopped depending on someone remembering.",
        "Added on-demand vehicle-health reports, so availability was a question the system could answer.",
        "Connected the specialised pieces \u2014 OCR fine handling, S&OP planning, mid-mile logistics and Glide intake \u2014 into one operating picture."
      ],
      outcome: "Over 80% less manual effort on vehicle availability alone. Not glamorous \u2014 very profitable.",
      recommendationRef: "Amr Mazen",
      story: [
        "Fleets don't fail at the exciting parts. They fail at the boring ones \u2014 a mis-typed VIN, a police notice that never becomes an invoice, a maintenance job nobody billed for.",
        "So we automated the boring parts. A work-order management system that mapped every job and invoice line across logistics, maintenance, repair, and inspection. OCR that turned a scanned traffic fine into a customer invoice. Automated monthly billing. On-demand vehicle-health reports. S&OP for the fleet, mid-mile planning for the trucks. A Glide app for VIN-scan check-in at intake.",
        "Result: 80%+ less manual effort just on vehicle availability. Not glamorous. Very profitable."
      ],
      coverImage: "/covers/mobility-b.svg",
      coverHeadline: "80% LESS MANUAL",
      coverCaption: "work orders \xB7 invoicing \xB7 vehicle health"
    },
    {
      id: "glide-intake",
      title: "Glide Intake \u2014 VIN-Scan Vehicle Check-In",
      category: "Mobility & Marketplaces",
      year: "2021",
      tags: [
        "MOBILE APP",
        "OPERATIONS"
      ],
      companies: [
        "cazoo"
      ],
      description: "A mobile app for taking cars in as they arrive at a Cazoo location \u2014 scan the VIN to check a vehicle in and confirm its details on the spot, replacing clipboard-and-spreadsheet intake.",
      oneLiner: "Scan a VIN, check the car in \u2014 intake in seconds instead of paperwork.",
      role: "Senior Product Manager",
      period: "Jun 2021 \u2013 Aug 2021",
      stack: [
        "iOS",
        "Android",
        "VIN scanning"
      ],
      problem: "Every car arriving at a hub or refurbishment centre has to be checked in and its details confirmed. Done on paper or in a spreadsheet, that is slow, easy to mistype, and invisible to everyone downstream until someone re-keys it \u2014 and a mis-typed VIN follows a vehicle through every system it touches afterwards.",
      approach: [
        "Built a mobile app for intake at the point the car physically arrives, rather than a desk process afterwards.",
        "Made VIN scanning the entry point, so the identifier is captured by the camera instead of typed.",
        "Confirmed vehicle details on the spot, so discrepancies surface while the car is still in front of you."
      ],
      outcome: "Vehicle intake became a scan rather than a form \u2014 feeding clean vehicle identity into the logistics and operations systems downstream.",
      coverImage: "/covers/mobility-b.svg",
      coverVideo: "/videos/glide-intake.mp4",
      coverPoster: "/videos/posters/glide-intake.jpg"
    },
    {
      id: "mid-mile-planning",
      title: "Mid-Mile Planning System",
      category: "Mobility & Marketplaces",
      year: "2021",
      tags: [
        "LOGISTICS",
        "PLANNING"
      ],
      companies: [
        "cazoo"
      ],
      description: "Planning the middle leg of vehicle logistics for Cazoo \u2014 moving whole truckloads of cars between refurbishment centres, distribution hubs and delivery, across European markets.",
      oneLiner: "Hub to hub, truckload by truckload \u2014 planning the leg nobody sees.",
      role: "Senior Product Manager",
      period: "Jul 2021 \u2013 Sep 2021",
      stack: [
        "Logistics planning",
        "Fleet operations"
      ],
      problem: "First mile and last mile get the attention; the middle leg is where the cost sits. Cars have to move between refurbishment centres and distribution hubs in whole truckloads, across markets, and a plan that looks fine on a spreadsheet fails the moment a hub is full or a truck is half empty.",
      approach: [
        "Built planning for the mid-mile leg specifically, rather than treating it as a gap between first and last mile.",
        "Planned at truckload level across refurbishment centres and distribution hubs.",
        "Fitted it to the wider first-mile / mid-mile / last-mile chain being stood up across Germany, France and Spain."
      ],
      outcome: "The middle leg of Cazoo's European vehicle logistics became something that could be planned rather than improvised.",
      coverImage: "/covers/mobility-b.svg",
      coverHeadline: "MID MILE",
      coverCaption: "hub \u2192 hub, truckload by truckload"
    },
    {
      id: "ocr-fine-handling",
      title: "OCR Digital Fine Handling",
      category: "Mobility & Marketplaces",
      year: "2020",
      tags: [
        "OCR",
        "AUTOMATION"
      ],
      companies: [
        "cluno"
      ],
      description: "Turning a scanned police notice into a customer invoice without a human retyping it \u2014 OCR-based traffic-fine handling for a subscription fleet.",
      oneLiner: "Scanned police notice in, customer invoice out \u2014 with nobody retyping it.",
      role: "Senior Product Manager",
      period: "May 2020 \u2013 Oct 2020",
      stack: [
        "OCR",
        "Automated invoicing"
      ],
      problem: "A subscription fleet collects traffic fines continuously, and each one arrives as a piece of paper naming the operator rather than the driver. Someone has to read it, identify the vehicle and the customer, and raise an invoice. It is pure manual cost, it scales linearly with the fleet, and every notice that falls through the cracks is money the business simply loses.",
      approach: [
        "Used OCR to read the scanned notice instead of having an operator transcribe it.",
        "Matched the notice to the vehicle and the customer responsible at that date automatically.",
        "Carried it straight through to a customer invoice, closing the loop end to end."
      ],
      outcome: "One of the boring, unglamorous processes that quietly caps how large a fleet a lean operations team can run \u2014 removed.",
      coverImage: "/covers/mobility-b.svg",
      coverHeadline: "NOTICE \u2192 INVOICE",
      coverCaption: "OCR in, customer invoice out"
    },
    {
      id: "sop-automation",
      title: "S&OP Process Automation",
      category: "Mobility & Marketplaces",
      year: "2019\u20132021",
      tags: [
        "S&OP",
        "FORECASTING"
      ],
      companies: [
        "cluno"
      ],
      description: "Sales & operations planning for a growing subscription fleet \u2014 automating the process that matches vehicle supply to customer demand.",
      oneLiner: "Matching vehicle supply to customer demand, without the monthly spreadsheet ritual.",
      role: "Senior Product Manager",
      period: "Mar 2019 \u2013 Nov 2021",
      stack: [
        "S&OP",
        "Supply chain",
        "Fleet planning"
      ],
      problem: "A car-subscription business lives or dies on whether the right vehicles are available when customers want them. Get it wrong in one direction and capital sits idle on a lot; get it wrong in the other and you turn customers away. Doing that planning by hand each cycle does not survive growth.",
      approach: [
        "Automated the sales & operations planning cycle instead of rebuilding it in a spreadsheet each period.",
        "Connected vehicle supply and availability to actual customer demand signals.",
        "Fed it into the wider supply-chain and logistics automation across the fleet."
      ],
      outcome: "Supply planning became a system rather than a monthly ritual \u2014 part of the lean operations engine behind the subscription fleet.",
      coverImage: "/covers/mobility-b.svg",
      coverHeadline: "SUPPLY MEETS DEMAND",
      coverCaption: "planning the fleet, not the spreadsheet"
    },
    {
      id: "zeiss-measurement-cell",
      title: "ZEISS AI Box \u2014 Robotic Inspection Cell",
      category: "Industrial & Vision",
      year: "2016\u20132017",
      tags: [
        "METROLOGY",
        "ROBOTICS"
      ],
      companies: [
        "zeissImt"
      ],
      description: "Robot-mounted optical measurement cell inspecting car-body parts next to the production line for Carl Zeiss IMT. Product owner, application engineer and software release manager from hardware & software requirements to release \u2014 piloted at Porsche Weissach and Daimler Sindelfingen, with cells in Germany, Shanghai and Detroit.",
      oneLiner: "A robot, a Zeiss camera and a live production line \u2014 optical inspection where the cars are actually built.",
      role: "Product Owner, Application Engineer & Software Release Manager",
      scale: "Cells in Germany, Shanghai & Detroit",
      period: "Mar 2016 \u2013 Feb 2017",
      stack: [
        "FANUC robotics",
        "ZEISS optical sensors",
        "Systems integration"
      ],
      metrics: [
        {
          value: "3",
          label: "continents shipped",
          note: "Germany \xB7 Shanghai \xB7 Detroit"
        },
        {
          value: "2",
          label: "OEM pilots",
          note: "Porsche Weissach \xB7 Daimler Sindelfingen"
        }
      ],
      problem: "Car-body parts were measured away from the line, which means delay between making a part and knowing whether it was good. Moving optical measurement next to production means a robot, a camera and a dozen software components have to agree \u2014 and measurement is unforgiving: if one link in the chain lies, the whole result is a lie.",
      approach: [
        "Took requirements in the room at Porsche Weissach and Daimler Sindelfingen rather than from a spec document.",
        "Got FANUC-certified to programme the robot personally, then mounted a ZEISS camera on it.",
        "Owned hardware and software requirements through to release as product owner, application engineer and release manager.",
        "Ran 'LAN parties' when things broke \u2014 engineers from every geography in one room, one problem, one week."
      ],
      outcome: "Cells piloted at Porsche and Daimler, and shipped in Germany, Shanghai and Detroit.",
      recommendationRef: "Mohsin Jamadar",
      story: [
        "This project put me on airplanes. Porsche in Weissach. Daimler in Sindelfingen. Understand the requirement in the room, not in a spec doc. Get FANUC-certified so I could programme the robot myself. Mount a Zeiss camera on it. Drop the whole cell into a live production line.",
        "The technical challenge was systems integration at its purest \u2014 a plethora of software components had to talk to each other, and every one of them had to work. Measurement is unforgiving; if one link in the chain lies, the whole result is a lie.",
        "When things broke, I ran what I called LAN parties \u2014 engineers from every geography in one room, one problem, one week. Leading people to solve a problem, not managing tickets. We failed as a team. We succeeded as a team. That's the frame I still lead by.",
        "Cells shipped in Germany, Shanghai, and Detroit."
      ],
      link: "https://pages.zeiss.com/RIM_AIBox_Info.html",
      coverImage: "/covers/engineering-a.svg",
      coverVideo: "/videos/ai-box.mp4",
      coverPoster: "/videos/posters/ai-box.jpg"
    },
    {
      id: "cad-reverse-engineering",
      title: "ZEISS Reverse Engineering \u2014 CAD Suite",
      category: "Industrial & Vision",
      year: "2011\u20132017",
      tags: [
        "CAD",
        "COMPUTER VISION"
      ],
      companies: [
        "zeissImt"
      ],
      description: "ZEISS Reverse Engineering \u2014 CAD reverse engineering and tool correction for mould making, built on point-cloud processing and BRep modelling (ACIS kernel). Technical lead from the first line of code at TCS, then owner through requirements, architecture, release, sales and support at MERZ for Carl Zeiss IMT. Followed by Merz CAD Workmate, an in-house CAD app later ported to Android and Microsoft HoloLens for holographic on-part reverse engineering.",
      oneLiner: "From a professor's algorithm to holograms \u2014 six years, two companies, one CAD product.",
      role: "Technical lead \u2192 product owner (requirements to sales & support)",
      team: "Hired and led 12 \u2192 25 engineers",
      scale: "Shipped to Carl Zeiss IMT",
      period: "Mar 2011 \u2013 2017",
      stack: [
        "C#",
        "WPF / MVVM",
        ".NET",
        "C++",
        "ACIS kernel",
        "Point clouds",
        "Android",
        "HoloLens"
      ],
      metrics: [
        {
          value: "25",
          label: "engineers hired & led"
        },
        {
          value: "6",
          label: "years, concept to HoloLens"
        }
      ],
      problem: "A mathematics professor had an algorithm that extracted surfaces from point clouds, so a physical part could be compared against its original CAD design. Turning that into a product mould-makers could rely on \u2014 reverse engineering and tool correction, robust enough to sell and support \u2014 was an entirely different problem from proving the maths.",
      approach: [
        "Wrote the first line of the new system, learning C#, WPF, MVVM, .NET and agile simultaneously.",
        "Built point-cloud processing and BRep modelling on the ACIS kernel for reverse engineering and tool correction in mould making.",
        "Hired and led the team in Bangalore \u2014 12 engineers, then 25.",
        "Rebuilt the product from scratch at MERZ with clean architecture and a smaller, stronger team, then owned it through requirements, architecture, release, sales and support.",
        "Extended it into Merz CAD Workmate, ported to Android and Microsoft HoloLens for holographic, on-part reverse engineering."
      ],
      outcome: "A product that carried Carl Zeiss IMT's reverse engineering for years \u2014 and the experience that taught me to trust work over words.",
      story: [
        "First trip to Germany. Twenty-something years old. Handed the code of a mathematics professor \u2014 Dr. Deets \u2014 whose algorithm extracted surfaces from point clouds so you could compare a physical part against its original CAD design.",
        "I wrote the first line of the new system. Learned C#, WPF, MVVM, the .NET framework, agile \u2014 everything new, all at once, and I loved every minute of it. Back in Bangalore I hired the rest of the team: 12, then 25 engineers. Some of them were sharp enough to find flaws in the code I'd already written. That ego bruise turned out to be the fastest way to learn.",
        "By 2013 my company was pushing to grow the team when I knew the product needed fewer, better people. I left. The client called the next day. I joined Merz Group and rebuilt the whole thing from scratch \u2014 clean architecture, right team, my call.",
        "Working with Germans permanently changed how I evaluate people. In India, if you asked someone 'do you know X?' and they knew 10%, they'd say yes. In Germany, if they knew 99% but not 100%, they'd say no. I stopped trusting words. I trust work.",
        "Later this became Merz CAD Workmate \u2014 an in-house CAD app we ported to Android and Microsoft HoloLens for holographic, on-part reverse engineering. From a professor's algorithm to holograms, in six years."
      ],
      link: "https://www.zeiss.de/messtechnik/software/zeiss-reverse-engineering.html",
      coverImage: "/covers/engineering-a.svg",
      coverHeadline: "2011\u20142017",
      coverCaption: "TCS \u2192 MERZ, ZEISS Reverse Engineering from scratch"
    },
    {
      id: "adaptive-clamping",
      title: "ZEISS Caligo & Adaptive Clamping",
      category: "Industrial & Vision",
      year: "2016\u20132017",
      tags: [
        "AUTOMATION",
        "CAD ALGORITHMS"
      ],
      companies: [
        "zeissImt",
        "clampingClient"
      ],
      description: "Two projects that turned me from a software person into a product person: Caligo DMS, a laser-projection measurement system where I first learned to solutionize with customers, and ROLEX \u2014 a universal clamping-pin field that adapts itself to any freeform part, computing per-pin Z-shifts from the CAD contour so the fixture physically reshapes to hold what it is about to machine.",
      oneLiner: "The project that turned a software person into a product person \u2014 plus a fixture that reshapes itself.",
      role: "Product Manager / Solution owner",
      period: "2016 \u2013 2017",
      stack: [
        "CAD contour processing",
        "Laser projection",
        "Modular libraries"
      ],
      problem: "Caligo DMS was a laser-projection measurement system that almost worked \u2014 and customers had stopped handing over requirements. They were showing daily friction instead. Separately, holding freeform parts for machining meant a bespoke fixture per part, which is slow and expensive.",
      approach: [
        "Stopped executing specifications and started solutionising with customers in front of the real problem.",
        "Turned that into work packages clean enough that engineers just built, with no back-and-forth.",
        "Designed ROLEX, a universal clamping-pin field that adapts to any freeform part \u2014 computing per-pin Z-shifts from the CAD contour so the fixture physically reshapes around what it is about to hold.",
        "Built it as modular libraries reusable across products, from feasibility prototype to delivery plan."
      ],
      outcome: "A fixture that reforms itself for any part \u2014 and the point where I stopped calling myself a software person and became a product person who could still write code.",
      story: [
        "Caligo doesn't look like the biggest project on this page, but it's the one that changed my identity.",
        "Customers weren't handing me requirements anymore. They were showing me their pain \u2014 the daily friction of working with a laser-projection measurement system that almost worked. For the first time I stopped executing and started solutionizing with them, then coming back to the team with a work package clean enough that engineers just built, no back-and-forth.",
        "That's when I stopped calling myself a software person. I was a product person who could still write code.",
        "In parallel, ROLEX: a universal clamping-pin field that shape-shifts to any freeform part. Compute the CAD contour, project per-pin Z-shifts, and the fixture literally reforms itself to hold whatever's about to be machined. Modular libraries, reusable across products, from feasibility prototype to delivery plan."
      ],
      coverImage: "/covers/engineering-a.svg",
      coverHeadline: "SELF-ADAPTING",
      coverCaption: "CAD contour \u2192 per-pin Z-shift, zero rework"
    },
    {
      id: "merz-cad-workmate",
      title: "MERZ CAD Workmate \u2014 Cross-Platform & AR/VR CAD",
      category: "Industrial & Vision",
      year: "2017",
      tags: [
        "AR / VR",
        "CAD"
      ],
      companies: [
        "merz"
      ],
      description: "Architect and product manager for a cross-platform CAD application with AR/VR support \u2014 later ported to Android and Microsoft HoloLens for holographic, on-part reverse engineering.",
      oneLiner: "CAD off the workstation and onto the part \u2014 cross-platform, and in holograms.",
      role: "Architect & Product Manager",
      period: "Feb 2017 \u2013 May 2017",
      stack: [
        "Cross-platform CAD",
        "Android",
        "Microsoft HoloLens",
        "AR / VR"
      ],
      problem: "CAD lives on a workstation, but the part it describes lives on the shop floor. Every time an engineer has to walk between the two, the comparison happens from memory. Getting CAD onto the floor means a cross-platform application \u2014 and eventually a headset that puts the model on the part itself.",
      approach: [
        "Architected an in-house CAD application that ran across platforms rather than one workstation.",
        "Designed it for AR/VR devices from the outset instead of retrofitting a viewer.",
        "Ported it to Android and Microsoft HoloLens for holographic, on-part reverse engineering."
      ],
      outcome: "The point where a professor's point-cloud algorithm ended up as a hologram overlaid on the physical part.",
      coverImage: "/covers/engineering-a.svg",
      coverHeadline: "CAD IN AR",
      coverCaption: "Android \xB7 HoloLens \xB7 on the part"
    },
    {
      id: "ct-defect-detection",
      title: "ML Defect Detection for CT Scans",
      category: "Industrial & Vision",
      year: "2017\u20132018",
      tags: [
        "MACHINE LEARNING",
        "AI SINCE 2017"
      ],
      companies: [
        "semiClient"
      ],
      description: "I was training neural networks for industrial inspection in 2017 \u2014 years before AI became fashionable. Machine-learning defect detection (Caffe) on computed-tomography scans of precision components for semiconductor manufacturing: volumetric scan import, defect classification by probability, type, size and rest-wall thickness, and a trainable master/user workflow where engineers teach the model new defect classes. Project lead from requirement definition through delivery.",
      oneLiner: "Training neural networks for industrial inspection in 2017 \u2014 years before AI was fashionable.",
      role: "Project lead \u2014 requirements through delivery",
      team: "In collaboration with Fraunhofer",
      period: "2017 \u2013 2018",
      stack: [
        "Caffe",
        "Neural networks",
        "CT / volumetric data"
      ],
      problem: "Precision pipes for semiconductor manufacturing had to be checked for micro-defects. A trained human spent a week per batch squinting at computed-tomography scans \u2014 slow, expensive, and inconsistent in exactly the way a person gets tired.",
      approach: [
        "Trained a Caffe model on labelled defects, classifying by probability, type, size and rest-wall thickness.",
        "Built volumetric scan import so CT data went straight into the pipeline.",
        "Designed a trainable master/user workflow so engineers could teach the model new defect classes as they appeared in production.",
        "Led the project from requirement definition through delivery, with Fraunhofer researchers advocating for neural nets harder than I did."
      ],
      outcome: "It worked \u2014 despite near-universal scepticism at the time. My first AI project, eight years before the rest of the industry arrived.",
      story: [
        "My first AI project. 2017. Pre-Transformer, pre-hype. In collaboration with Fraunhofer, whose researchers advocated for neural nets harder than I did.",
        "The problem: precision pipes for semiconductor manufacturing had to be inspected for micro-defects. A trained human spent a week per batch, squinting at CT scans. We trained a Caffe model on labelled defects \u2014 probability, type, size, rest-wall thickness \u2014 with a master/user workflow so an engineer could teach the model new defect classes as they appeared in production.",
        "Every time I told someone what I was working on, they thought it wouldn't work. It worked. That's when the 2008 daydream came back to me \u2014 a world where you type in English and machines write code. Fifteen years early. But the direction was right."
      ],
      coverImage: "/covers/engineering-a.svg",
      coverVideo: "/videos/ct-defect.mp4",
      coverPoster: "/videos/posters/ct-defect.jpg"
    },
    {
      id: "product-leadership",
      title: "Product & Engineering Leadership",
      category: "Leadership",
      year: "2013\u2013present",
      tags: [
        "LEADERSHIP",
        "TEAMS"
      ],
      companies: [
        "zeissImt",
        "cluno",
        "cazoo",
        "autoscout24",
        "cubonic"
      ],
      description: "Building and leading cross-functional teams across engineering, product, and design \u2014 from three departments at MERZ to app teams at AutoScout24 \u2014 hiring, delivery cadence, and a bias toward shipping useful software over slideware.",
      oneLiner: "Seven teams, seven geographies, one product \u2014 and the operating rule underneath all of it.",
      role: "Head of Software \u2192 Head of Product / Head of Digital Solutions",
      team: "Up to 7 teams \xB7 4 PMs \xB7 24 engineers",
      scale: "MERZ \xB7 Cluno \xB7 Cazoo \xB7 AutoScout24 \xB7 CUBONIC",
      period: "2013 \u2013 present",
      metrics: [
        {
          value: "7",
          label: "teams across 7 geographies",
          note: "at MERZ, aged 25"
        },
        {
          value: "5",
          label: "companies led in",
          note: "industrial \u2192 mobility \u2192 AI"
        }
      ],
      problem: "Leading software people is mostly not a software problem. Across three departments at MERZ, app teams at AutoScout24 and product teams at Cluno, Cazoo and CUBONIC, the recurring question is the same: how do you keep people motivated and aligned across time zones, and how do you hire so that shipping is the default?",
      approach: [
        "Led seven teams across seven geographies on one product after being promoted to Head of Software at MERZ at 25.",
        "Hired against three signals every time: is this person telling the truth about their CV, can they think under pressure, and can they communicate.",
        "Built on three pillars \u2014 Transparency \u2192 Trust \u2192 Positivity.",
        "Applied one operating rule: judge people by what they ship, not what they promise, then give them the room to ship."
      ],
      outcome: "Teams that shipped useful software instead of slideware, across industrial metrology, mobility marketplaces and AI.",
      recommendationRef: "Derek Charter",
      story: [
        "Promoted to Head of Software at Merz at 25 \u2014 not because I was close to the CEO, but because I'd shown him what the group could do beyond one or two customers. Seven teams, seven geographies, one product. That's where I learned that keeping people motivated across time zones is the actual job.",
        "Since then: PMs and engineers at Cluno, Cazoo, AutoScout24, and CUBONIC. Same hiring signal every time \u2014 is this person telling the truth about their CV, can they think under pressure, and can they communicate? Genius that can't communicate loses to competence that can.",
        "The way I lead sits on three pillars: Transparency \u2192 Trust \u2192 Positivity. And underneath all of it, one operating rule: judge people by what they ship, not what they promise. Then give them the room to ship."
      ],
      coverImage: "/covers/leadership-a.svg"
    }
  ]
};

// src/lib/mcp/tools/list-projects.ts
var projects = projects_default.projects;
var list_projects_default = defineTool2({
  name: "list_projects",
  title: "List projects",
  description: "List Utpal Das's portfolio projects. Optionally filter by category, tag, or company. Returns summaries \u2014 use get_project for full case-study stories.",
  inputSchema: {
    category: z.string().optional().describe("Filter by category (e.g. 'AI Systems', 'Mobility & Marketplaces')."),
    tag: z.string().optional().describe("Filter by a tag (case-insensitive)."),
    company: z.string().optional().describe("Filter by a company id (e.g. 'cubonic', 'autoscout24', 'cluno').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, tag, company }) => {
    let items = projects;
    if (category) items = items.filter((p) => p.category.toLowerCase() === category.toLowerCase());
    if (tag) items = items.filter((p) => p.tags.some((t) => t.toLowerCase() === tag.toLowerCase()));
    if (company) items = items.filter((p) => p.companies.includes(company));
    const summaries = items.map((p) => ({
      id: p.id,
      title: p.title,
      category: p.category,
      year: p.year,
      companies: p.companies,
      tags: p.tags,
      description: p.description
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summaries, null, 2) }],
      structuredContent: { count: summaries.length, projects: summaries }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var projects2 = projects_default.projects;
var get_project_default = defineTool3({
  name: "get_project",
  title: "Get project",
  description: "Get the full case study for a project by id, including the narrative story sections.",
  inputSchema: {
    id: z2.string().min(1).describe("Project id, e.g. 'autoscout24-apps' or 'agentic-platform'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const project = projects2.find((p) => p.id === id);
    if (!project) {
      return {
        content: [{ type: "text", text: `No project found with id '${id}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  }
});

// src/lib/mcp/tools/list-companies.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";

// content/companies.json
var companies_default = {
  companies: [
    {
      key: "cubonic",
      name: "CUBONIC",
      url: "https://cubonic.de",
      logo: "/logos/cubonic.png"
    },
    {
      key: "autoscout24",
      name: "AutoScout24",
      url: "https://www.autoscout24.de",
      logo: "/logos/autoscout24.png"
    },
    {
      key: "cazoo",
      name: "Cazoo",
      url: "https://www.cazoo.co.uk",
      logo: "/logos/cazoo.png"
    },
    {
      key: "cluno",
      name: "Cluno",
      url: "https://www.cazoo.co.uk",
      logo: null
    },
    {
      key: "zeissImt",
      name: "Carl Zeiss IMT GmbH",
      url: "https://www.zeiss.com/metrology",
      logo: "/logos/zeiss.png"
    },
    {
      key: "merz",
      name: "MERZ Group",
      url: null,
      logo: null
    },
    {
      key: "semiClient",
      name: "Semiconductor industry",
      url: null,
      logo: null
    },
    {
      key: "clampingClient",
      name: "Clamping-technology manufacturer",
      url: null,
      logo: null
    },
    {
      key: "tcs",
      name: "Tata Consultancy Services",
      url: "https://www.tcs.com",
      logo: "/logos/tcs.png"
    },
    {
      key: "extend3d",
      name: "Extend3D",
      url: "https://www.extend3d.com",
      logo: "/logos/extend3d.svg"
    },
    {
      key: "nal",
      name: "National Aerospace Laboratories",
      url: "https://www.nal.res.in",
      logo: null
    },
    {
      key: "meggitt",
      name: "Meggitt",
      url: "https://www.meggitt.com",
      logo: null
    },
    {
      key: "negele",
      name: "Anderson-Negele",
      url: "https://www.anderson-negele.com",
      logo: "/logos/anderson-negele.png"
    },
    {
      key: "hireplusplus",
      name: "HirePlusPlus",
      url: "https://hireplusplus.com",
      logo: null
    },
    {
      key: "labs",
      name: "UtpalDasLabs",
      url: "https://github.com/UtpalDasLabs",
      logo: null
    }
  ]
};

// src/lib/mcp/tools/list-companies.ts
var list_companies_default = defineTool4({
  name: "list_companies",
  title: "List companies",
  description: "List the companies Utpal has worked with, including role summaries where available.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(companies_default, null, 2) }],
    structuredContent: companies_default
  })
});

// src/lib/mcp/tools/list-recommendations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";

// content/recommendations.json
var recommendations_default = {
  recommendations: [
    {
      author: "Louis Badcock",
      role: "Chief Product and Technology Officer, World of Books Group",
      context: "Led the Asset Finance team at Cazoo",
      company: "Cazoo",
      quote: "Utpal is a great product manager who led our Asset Finance team at Cazoo. He's a strong collaborator and quick to build effective working relationships. Utpal has a passion for product management, always focusing on results and constructively challenging the why of his product to ensure it is focused on delivering genuine business value. Always striving to learn and better himself, Utpal has a calm, affable attitude and shows resilience in the face of adversity. He's a pleasure to work with.",
      featured: true
    },
    {
      author: "Dr. Veronika von Heise-Rotenburg",
      role: "CFO & Gesch\xE4ftsf\xFChrerin, Everphone",
      context: "Worked together at Cluno and Cazoo",
      company: "Cluno",
      quote: "Utpal was responsible for the digitization of several processes, such as car handover to customers and the creation of a partner portal, which enabled suppliers to collaborate digitally instead of manually with our operations team. Bringing in his experience in innovation, product knowledge and efficiency, he was able to support Cluno's growth and raise efficiency by building lean operations.",
      featured: true
    },
    {
      author: "Tino Kapolka",
      role: "Head of Product, AutoScout24",
      context: "Collaborated on Search across App and Web",
      company: "AutoScout24",
      quote: "Working with Utpal was always very constructive and outcome driven. He was bringing new perspectives into discussions and shared valuable learnings from past experiences. I especially enjoyed his very supportive and pragmatic working mode, which has helped to successfully drive cross-team initiatives. Utpal is a great match for all customer centric product organizations, who are looking for an experienced leader with a strong passion to drive outcome.",
      featured: true
    },
    {
      author: "Derek Charter",
      role: "Technology Strategy and Operations Director, IVC Evidensia",
      context: "Worked together at Cazoo",
      company: "Cazoo",
      quote: "I've worked with dozens of Product Managers over the years. All the very best combine advanced product discovery skills and formal product management techniques with a natural empathy and affinity for people, users and customers. Utpal embodies all these qualities at the highest level. He has a profound theoretical knowledge and knows how to put it in practice to achieve real product value.",
      featured: true
    },
    {
      author: "Nikita Belokopytov",
      role: "Staff Applied AI Engineer, Bluefish",
      context: "Built native apps strategy at AutoScout24",
      company: "AutoScout24",
      quote: "Utpal has proven to be a passionate, driven, trustworthy partner. He has always been looking out for his team and giving them enough space to develop. As a product leader his approach was to inform his decisions by data and enhance them with the insights he'd obtained from close collaboration with our international offices and business stakeholders. Utpal is a very strong product leader, who no doubt will leave a mark on the industry.",
      featured: true
    },
    {
      author: "Lee Smith",
      role: "Product Designer, Cazoo",
      context: "Worked together at Cazoo",
      company: "Cazoo",
      quote: "Working with Utpal has been one of the highlights of my time working at Cazoo. He brings advanced formal product knowledge, the ability to rally a team around a vision and a relentless focus on delivering genuine value to stakeholders and users. He affords the right amount of autonomy but is always there to step in with support where needed.",
      featured: false
    },
    {
      author: "Harriet May",
      role: "Lead Product Manager, Valtech",
      context: "Neighbouring finance tech teams at Cazoo",
      company: "Cazoo",
      quote: "Utpal is curious, friendly, and tenacious, which means he asks all the right questions, does so warmly, but will not stop until he has his answer! I was inspired by Utpal's clear vision for his team, impressive discovery work, and drive to understand and influence the most impactful metrics. Everyone who works with Utpal will learn a lot from him.",
      featured: false
    },
    {
      author: "Sharath Ganesh Pai",
      role: "Test Automation, Freetrade",
      context: "Two years together at Cluno",
      company: "Cluno",
      quote: "He was spearheading the product department for the integration of our operations work in our Salesforce platform, and the associated mobile apps. The highlight was building the logistics platform from scratch that helped save tons of time for a lot of people \u2014 both B2C & B2B customers as well as our internal logistics colleagues.",
      featured: false
    },
    {
      author: "Amr Mazen",
      role: "Co-Founder, Sylndr",
      context: "Led Ops product at Cluno",
      company: "Cluno",
      quote: "Utpal has shown great passion and dedication leading our Ops product at Cluno. His eye to detail and growth mindset has tremendously helped us deliver a great customer experience and lean operations.",
      featured: false
    },
    {
      author: "Uygar Boynudelik",
      role: "Product Manager, HD PLUS GmbH",
      context: "Worked together in mobility",
      company: "Cluno",
      quote: "Utpal is essentially an outstanding Product Manager with a strong technical background. He has a very genuine interest, experience and holistic view in the mobility space. He is open minded, eager to learn and a great team player.",
      featured: false
    },
    {
      author: "Annika Kaps",
      role: "Senior Product Owner, Interhyp Gruppe",
      context: "Fellow product managers at Cluno",
      company: "Cluno",
      quote: "Utpal's structured and focused way of working is impressive. He takes ownership and never lets his product vision out of sight. With his vast experience and passion, he has left a true mark at Cluno and is a much appreciated colleague.",
      featured: false
    },
    {
      author: "Mohsin Jamadar",
      role: "Solutions Architect, PanGulfTech",
      context: "Worked together at TCS",
      company: "TCS",
      quote: "Utpal has a good knowledge of C++, C# and OOP concepts. His approach towards work is proactive and well planned. Ready to take responsibilities and can mentor well. Along with this he has great communication skills and can handle things well without pressure.",
      featured: false
    }
  ]
};

// src/lib/mcp/tools/list-recommendations.ts
var list_recommendations_default = defineTool5({
  name: "list_recommendations",
  title: "List recommendations",
  description: "List public recommendations and endorsements for Utpal Das.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(recommendations_default, null, 2) }],
    structuredContent: recommendations_default
  })
});

// src/lib/mcp/index.ts
var projectRef = "hwlpdguadmofhlftjznl";
var mcp_default = defineMcp({
  name: "utpal-das-portfolio",
  title: "Utpal Das \u2014 Portfolio",
  version: "0.2.0",
  instructions: "Authenticated MCP server for Utpal Das's portfolio. Sign-in required. Read-only tools: get_profile, list_projects, get_project, list_companies, list_recommendations.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, list_projects_default, get_project_default, list_companies_default, list_recommendations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
